.TH UAT 1 2016-11-24 UAT "Usenet Archive Toolkit"
.SH NAME
uat-repack-lz4 \- recompress Zstandard archive to LZ4 format
.SH SYNOPSIS
.I uat-repack-lz4
<archive>
.SH DESCRIPTION
Repackage Zstandard archive to LZ4 format, suitable for working with data.
.SH "SEE ALSO"
.ad l
.nh
.BR \%uat-repack-zstd (1)
