.TH UAT 1 2016-11-24 UAT "Usenet Archive Toolkit"
.SH NAME
uat-extract-msgid \- build message identifier table
.SH SYNOPSIS
.I uat-extract-msgid
<archive>
.SH DESCRIPTION
Extracts unique identifier of each message and builds reference table for
fast access to any message through its ID.
.SH NOTES
Requires LZ4 archive.
