.TH UAT 1 2016-11-24 UAT "Usenet Archive Toolkit"
.SH NAME
uat-lexdist \- calculate distances between words
.SH SYNOPSIS
.I uat-lexdist
<archive>
.SH DESCRIPTION
This utility calculates distances between words. This information is used to
perform fuzzy search.
.SH NOTES
Requires LZ4 archive processed using
.I uat-lexicon
.SH "SEE ALSO"
.ad l
.nh
.BR \%uat-lexicon (1)
