.TH UAT 1 2016-11-24 UAT "Usenet Archive Toolkit"
.SH NAME
uat-nntp-get \- get messages from NNTP server
.SH SYNOPSIS
.I uat-nntp-get
<server>
<input>
.SH DESCRIPTION
This utility retrieves messages from NNTP server.
.SH OPTIONS
.TP
.BR server
NNTP server.
.TP
.BR input
Text file with one
.I group lastarticle
entry per line.
.SH NOTES
Last article in a newsgroup indicates the last message which you have. Only
newer ones will be retrieved, excluding this one.
.SH "SEE ALSO"
.ad l
.nh
.BR \%uat-google-groups (1)
