.TH UAT 1 2016-11-24 UAT "Usenet Archive Toolkit"
.SH NAME
uat-import-source-maildir \- import messages from directory tree
.SH SYNOPSIS
.I uat-import-source-maildir
<source>
<destination>
.SH DESCRIPTION
Import from a directory tree where each file is a separate message (for
example slrnpull produces this with extra-simple setup required to get it
working).

This will produce archive in LZ4 format, suitable for working with data.
.SH "SEE ALSO"
.ad l
.nh
.BR \%google-groups (1),
.BR \%import-source-maildir-7z (1),
.BR \%import-source-mbox (1)
