.TH UAT 1 2016-11-24 UAT "Usenet Archive Toolkit"
.SH NAME
uat-query \- query Zstandard archive
.SH SYNOPSIS
.I uat-query
<archive>
.SH DESCRIPTION
Perform queries on Zstandard archive using end-user libuat interface.
Supported operations include: viewing messages, retrieving message parent
and children, performing searches, etc.
.SH NOTES
Requires completely processed archive.
.SH "SEE ALSO"
.ad l
.nh
.BR \%uat-libuat (1),
.BR \%uat-package (1),
.BR \%uat-query-raw (1)
