.TH UAT 1 2016-11-24 UAT "Usenet Archive Toolkit"
.SH NAME
uat-repack-zstd \- recompress archive to Zstandard format
.SH SYNOPSIS
.I uat-repack-zstd
[-z level]
[-s power]
<archive>
.SH DESCRIPTION
Builds common dictionary for all messages and recompresses them to a
Zstandard meta+payload+dict database. This format provides high compression
ratio with the ability to randomly access messages and is suitable for final
message storage.

Compression is performed using all available CPU cores.
.SH OPTIONS
Control switches modify the compression performance. More compression equals
more CPU and memory usage. Default values are appropriate for production
archive deployment and are very resource exhausting.
.TP
.BR \-z\fI\ level
Zstandard compression level. Consult https://github.com/facebook/zstd for
more information.
.TP
.BR \-s\fI\ power
Set maximum data sample size used for building dictionary to 2^\fIpower\fR
bytes.  Valid values: 10-31.
.I uat-repack-zstd
requires 10*N bytes of memory to build N-byte sized dictionary.
.TP
.BR \-S\fI\ selectivity
Set selectivity level. This handles balance between compactness of the
dictionary and efficiency of compression.
.SH EXAMPLE
The following table shows how dictionary sample size may influence
compressed data size for a 1 GB archive.
.TS
tab(;);
c c c
n n n .
Sample size ; Dictionary size ; Data size
8 MB ; 325 KB ; 375 MB
16 MB ; 349 KB ; 369 MB
32 MB ; 400 KB ; 364 MB
64 MB ; 448 KB ; 357 MB
128 MB ; 453 KB ; 352 MB
256 MB ; 452 KB ; 346 MB
512 MB ; 461 KB ; 333 MB
1024 MB ; 483 KB ; 324 MB
.TE

Here are output data sizes obtained using various compression levels on a
62\ MB archive. Dictionary size was constant at 364\ KB. Time was measured
with a small (128\ KB) dictionary.
.TS
tab(;);
c c c
n n n .
Level ; Data size ; Time
1 ; 25104384 ; 0.31s
2 ; 23509818 ; 0.30s
3 ; 22718925 ; 0.35s
4 ; 22462288 ; 0.44s
5 ; 21826232 ; 0.48s
6 ; 21164245 ; 0.51s
7 ; 20857144 ; 0.53s
8 ; 20461183 ; 0.53s
9 ; 20427667 ; 0.87s
10 ; 20312570 ; 1.23s
11 ; 20312570 ; 1.38s
12 ; 20254263 ; 1.47s
13 ; 20254263 ; 1.63s
14 ; 20227239 ; 1.86s
15 ; 20189331 ; 2.08s
16 ; 20189331 ; 2.20s
17 ; 20011183 ; 2.23s
18 ; 19975813 ; 2.51s
19 ; 19863161 ; 2.22s
20 ; 19809713 ; 2.22s
21 ; 19791759 ; 2.21s
22 ; 19791740 ; 2.27s
.TE
.SH NOTES
Requires LZ4 archive.
.SH "SEE ALSO"
.ad l
.nh
.BR \%uat-repack-lz4 (1),
.BR \%uat-update-zstd (1)
