name: Arch Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm --needed cmake ninja gmime3 nodejs git
    - uses: actions/checkout@v4
    - run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - run: cmake --build build
    - run: cmake --install build
      env:
        DESTDIR: ${{ github.workspace }}/install
    - run: tar -zcvf install.tar.gz -C install .
    - uses: actions/upload-artifact@v4
      with:
        name: install
        path: install.tar.gz
